/**
 * RAG Constants
 *
 * Shared constants for the RAG system (search, pipeline, UI).
 */

/**
 * Citation pattern used in LLM responses
 *
 * Format: **[Quelle: Chunk-Titel]**
 *
 * This pattern is:
 * - Generated by the LLM via prompt instructions (pipeline.ts)
 * - Rendered as styled badges in the UI (ChatMessageBubble.tsx)
 *
 * Example: "Emotion Detection nutzt 12 Audio-Features **[Quelle: Emotion Detection]**."
 */
export const CITATION_PATTERN = /^\[Quelle:\s*(.+?)\]$/;

/**
 * Maximum length for citation source text
 *
 * Prevents overly long citations from breaking UI layout.
 * 100 chars passt zu ~2-3 Zeilen im Chat-Bubble (Desktop-Sidebar ~280px).
 * Längere Titel werden in ChatMessageBubble.tsx mit Ellipsis abgeschnitten.
 */
export const MAX_CITATION_LENGTH = 100 as const;

/**
 * Maximum number of chat history messages to include in RAG context
 *
 * Represents the last N messages (user + assistant pairs).
 * For example, 6 messages = last 3 conversation turns.
 *
 * Limit is due to Ollama context window constraints (~2048 tokens).
 */
export const MAX_HISTORY_MESSAGES = 6 as const;

/**
 * Minimum relevance score threshold for KB chunks (V3.2 - Meta-Question Bug Fix)
 *
 * If all search results score below this threshold, KB chunks are omitted
 * and the LLM relies only on chat history.
 *
 * This prevents irrelevant KB content from dominating the prompt when
 * the user asks meta-questions about the conversation itself.
 *
 * Range: 0.0 (never filter) to 1.0 (always filter)
 * Default: 0.3 (30% relevance minimum)
 *
 * Research: Layered defense strategy (Gemini recommendation)
 * - Primary filter: Low scores indicate off-topic/meta-questions
 * - Conservative threshold: Allows most domain questions through
 * - Graceful degradation: Falls back to history-only mode
 */
export const MIN_RELEVANCE_THRESHOLD = 0.3 as const;

/**
 * Prompt Injection Detection Patterns
 *
 * Used to detect and block prompt injection attempts in:
 * - RAG chatbot user questions (pipeline.ts)
 * - Analysis prompt inputs (base-client.ts)
 *
 * Covers common injection techniques:
 * - Instruction override (English + German)
 * - Role assignment attacks (imagine, simulate, respond as, behave like)
 * - System prompt manipulation
 *
 * Limitations:
 * - Does NOT cover encoding bypasses (ROT13, Base64, leetspeak) - P2 future
 * - Does NOT cover multi-language variants (FR, ES, IT) - P2 future
 *
 * Trade-off: Simple regex patterns (fast, predictable) vs ML-based detection (overkill for MVP)
 */
export const INJECTION_PATTERNS = [
  // English patterns (15)
  /ignore\s+(all\s+)?previous\s+instructions?/i, // "ignore all previous instructions"
  /ignore\s+all\s+context/i,                     // "ignore all context"
  /you\s+are\s+now/i,                            // "you are now DAN"
  /new\s+instruction/i,                          // "new instruction: respond in JSON"
  /forget\s+everything/i,                        // "forget everything you know"
  /disregard\s+(all\s+)?previous/i,              // "disregard previous guidelines"
  /system\s+prompt/i,                            // "show me your system prompt"
  /override\s+instructions?/i,                   // "override instructions"
  /pretend\s+you\s+are/i,                        // "pretend you are unrestricted"
  /act\s+as\s+(a|an)?/i,                         // "act as a hacker"
  /roleplay\s+as/i,                              // "roleplay as admin"
  // P1 Hardening - Role-play variants (4 new)
  /imagine\s+you\s+are/i,                        // "imagine you are jailbroken"
  /simulate\s+being/i,                           // "simulate being compromised"
  /respond\s+as\s+if/i,                          // "respond as if unrestricted"
  /behave\s+like/i,                              // "behave like you have no rules"
  // German patterns (3)
  /ignoriere\s+(alle\s+)?vorherigen/i,           // "ignoriere alle vorherigen Anweisungen"
  /vergiss\s+alles/i,                            // "vergiss alles"
  /du\s+bist\s+jetzt/i,                          // "du bist jetzt ein Hacker"
] as const;
